version: '3.4'

services:
  lbhaddressesapi:
    #image: lbhaddressesapi
    build:
      context: ./HackneyAddressesAPI
      dockerfile: Dockerfile
      args:
        - VERSION_SUFFIX
    ports:
      - 3000:80
    links:
     - stubaddressdb
  lbhaddressesapitest:
    #image: lbhaddressesapitest
    build:
      context: ./lbhaddressesapitest
      dockerfile: Dockerfile
    links:
     - lbhaddressesapi
     - stubaddressdb
  stubaddressdb:
    #image: stubaddressdb
    build:
      context: ./stubaddressdb
      dockerfile: Dockerfile
    ports:
      - 1433:1433