version: '3.7'

services:
  lbhaddressesapi:
    image: lbhaddressesapi
    build:
      context: .
      dockerfile: HackneyAddressesAPI/Dockerfile
      args:
        - VERSION_SUFFIX
    ports:
      - 3000:80
    links:
     - stubaddressdb
  lbhaddressesapitest:
    image: lbhaddressesapitest
    build:
      context: .
      dockerfile: LBHAddressesAPITest/Dockerfile
    links:
     - lbhaddressesapi
     - stubaddressdb
  stubaddressdb:
    image: stubaddressdb
    build:
      context: .
      dockerfile: StubAddressDB/Dockerfile
    ports:
      - 1433:1433

