version: '3.7'

services:
  lbhaddressesapi:
    image: lbhaddressesapi
    build:
      context: HackneyAddressesAPI/
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    volumes:
      - './lbhaddressesapi:/app'
      - 'out:/app/out'
      - 'obj:/app/obj'
      - 'bin:/app/bin'

  stubaddressdb:
    image: stubaddressdb
    build:
      context: .
      dockerfile: StubAddressDB/Dockerfile
    ports:
      - 6666:1433

  lbhaddressesapitest:
    image: lbhaddressesapitest
    build:
      context: .
      dockerfile: LBHAddressesAPITest/Dockerfile
    links:
      - stubaddressdb
volumes:
  obj:
  bin:
  out:
