version: '3.7'

services:
  lbhaddressesapi:
    image: lbhaddressesapi
    build:
      context: HackneyAddressesAPI/
      dockerfile: ./Dockerfile
    ports:
      - 9000:80

  stubaddressdb:
    image: stubaddressdb
    build:
      context: .
      dockerfile: StubAddressDB/Dockerfile
    ports:
      - 6666:1433

  lbhaddressesapitest:
    image: lbhaddressesapitest
    build:
      context: .
      dockerfile: LBHAddressesAPITest/Dockerfile
    links:
      - stubaddressdb
