CREATE DATABASE StubAdd;
GO

USE StubAdd;
GO

CREATE TABLE [dbo].[combined_address](
	[LPI_KEY] VARCHAR(14) NULL,
	[LPI_LOGICAL_STATUS] VARCHAR(18) NULL,
	[LPI_OFFICIAL_FLAG] VARCHAR(1) NULL,
	[LPI_START_DATE] INT NOT NULL,
	[LPI_END_DATE] INT NULL,
	[LPI_LAST_UPDATE_DATE] INT NOT NULL,
	[USRN] INT NOT NULL,
	[UPRN] FLOAT NOT NULL,
	[PARENT_UPRN] FLOAT NULL,
	[BLPU_START_DATE] INT NULL,
	[BLPU_END_DATE] INT NULL,
	[BLPU_STATE] SMALLINT NULL,
	[BLPU_STATE_DATE] INT NULL,
	[BLPU_CLASS] VARCHAR(4) NULL,
	[USAGE_DESCRIPTION] VARCHAR(160) NULL,
	[USAGE_PRIMARY] VARCHAR(160) NULL,
	[PROPERTY_SHELL] BIT NULL,
	[EASTING] NUMERIC(12, 4) NULL,
	[NORTHING] NUMERIC(12, 4) NULL,
	[RPA] [tinyint] NULL,
	[ORGANISATION] NVARCHAR(100) NULL,
	[SAO_TEXT] NVARCHAR(90) NULL,
	[UNIT_NUMBER] NVARCHAR(17) NULL,
	[LPI_LEVEL] NVARCHAR(30) NULL,
	[PAO_TEXT] NVARCHAR(90) NULL,
	[BUILDING_NUMBER] NVARCHAR(17) NULL,
	[STREET_DESCRIPTION] NVARCHAR(100) NOT NULL,
	[STREET_ADMIN] VARCHAR(7) NOT NULL,
	[LOCALITY] NVARCHAR(35) NULL,
	[POSTALLY_ADDRESSABLE] VARCHAR(1) NOT NULL,
	[NEVEREXPORT] BIT NOT NULL,
	[POSTTOWN] NVARCHAR(30) NULL,
	[POSTCODE] VARCHAR(8) NULL,
	[POSTCODE_NOSPACE] VARCHAR(8) NULL,
	[LONGITUDE] FLOAT NULL,
	[LATITUDE] FLOAT NULL,
	[GAZETTEER] VARCHAR(5) NOT NULL
) ON [PRIMARY] 
GO

INSERT INTO [dbo].[combined_address]
           ([LPI_KEY]
           ,[LPI_LOGICAL_STATUS]
           ,[LPI_OFFICIAL_FLAG]
           ,[LPI_START_DATE]
           ,[LPI_END_DATE]
           ,[LPI_LAST_UPDATE_DATE]
           ,[USRN]
           ,[UPRN]
           ,[PARENT_UPRN]
           ,[BLPU_START_DATE]
           ,[BLPU_END_DATE]
           ,[BLPU_STATE]
           ,[BLPU_STATE_DATE]
           ,[BLPU_CLASS]
           ,[USAGE_DESCRIPTION]
           ,[USAGE_PRIMARY]
           ,[PROPERTY_SHELL]
           ,[EASTING]
           ,[NORTHING]
           ,[RPA]
           ,[ORGANISATION]
           ,[SAO_TEXT]
           ,[UNIT_NUMBER]
           ,[LPI_LEVEL]
           ,[PAO_TEXT]
           ,[BUILDING_NUMBER]
           ,[STREET_DESCRIPTION]
           ,[STREET_ADMIN]
           ,[LOCALITY]
           ,[POSTALLY_ADDRESSABLE]
           ,[NEVEREXPORT]
           ,[POSTTOWN]
           ,[POSTCODE]
           ,[POSTCODE_NOSPACE]
           ,[LONGITUDE]
           ,[LATITUDE]
           ,[GAZETTEER])
     VALUES
          ()
GO
