version: 2
jobs:
  check:
    machine: 
      image: circleci/classic:201808-01 #used to push docker form 17 to 18 use 'machine: true' when this is no longer needed
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build projects
          command: docker-compose build --build-arg VERSION_SUFFIX=$CIRCLE_BUILD_NUM
      - run:
          name: Run tests
          command: docker-compose run -e LLPGConnectionString="server=tcp:stubaddressdb; database=StubAdd; Integrated Security=False;User ID=sa;Password=Rooty-Tooty" --rm lbhaddressesapitest dotnet test
workflows:
  version: 2
  continuous_delivery:
    jobs:
      - check